train:
  seed: 2025
  epochs: 2000
  save_path: logs/dynamics_flow_mixed
  log_interval: 10
  val_interval: 1

optimizer:
  lr: 0.0005
  weight_decay: 1e-16

scheduler:
  min_lr: 0.000001
  patience: 40
  factor: 0.8
  stop_tolerance: 400

data:
  transition1x_path: /inspire/qb-ilm/project/chemicalreaction/czxs25220150/projects/TS-DFM/Data/Transition1x.h5  # Set to the Transition1x HDF5 file.
  rgd1_cache_path: /inspire/qb-ilm/project/chemicalreaction/czxs25220150/projects/TS-DFM/Data/processed/rgd1_full
  batch_size: 256
  num_workers: 0

dynamic_model:
  parameters:
    hidden_dim:256              #128
    cutoff: 20.0
    max_embedding: 100
    num_layers: 12              #6
